export interface IAsset {
  eth?: number;
  mai?: number;
  usdc?: number;
  usdt?: number;
  ezeth?: number;
  pufeth?: number;
  rseth?: number;
  grai?: number;
  wbtc?: number;
  sweth?: number;
  weeth?:number;
  wrseth?:number;
  unieth?:number;
  dai?: number;
  weth:number;
  okb?: number;
  usdb?:number;
  lusd?: number;
  usdce?: number;
  busd?: number;
  cake?: number;
  mute?: number;
  sword?: number;
  vc?: number;
  wsteth?: number;
  manta?: number;
  stone?: number;
  tia?: number;
  wstEth?: number;
  wusdm?: number;
}
