export interface IAsset {
  eth?: number;
  usdc?: number;
  usdt?: number;
  manta?: number;
  stone?: number;
  tia?: number;
  wbtc?: number;
  wsEth?: number;
  wusdm?: number;
  ezeth?: number;
  grai?: number;
  mai?: number;
  okb?: number;
  dai?: number;
  lusd?: number;
  usdce?: number;
  busd?: number;
  cake?: number;
  mute?: number;
  sword?: number;
  vc?: number;
  wsteth?: number;
  pufeth?: number;
  rseth?: number;
  wefeth?: number;
  sweth?: number;
  lido?: number;
}
