name: Sample Workflow
on:
  push: # enabling push event on master branch to fire the workflow
    branches: ["ani-dev", "github-actions"]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: yarn

      - name: Code Linting
        run: yarn lint
