name: Sample Workflow
on:
  push: # enabling push event on master branch to fire the workflow
    branches:
      - ani-dev
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
