name: Lint
on:
  push: # enabling push event on master branch to fire the workflow
    branches: ["ani-dev", "el-dev"]
jobs:
  eslint-check: #job name
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn
      - name: Code Linting
        run: yarn lint
